config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', path_names: { sign_in: 'login', sign_out: 'logout' }, :controllers => { registrations: 'user_registrations' }
  resources :users
  get 'static_pages/index'

  get 'static_pages/about'

  get 'static_pages/contact'
 
  root 'articles#index'

  post 'static_pages/thank_you'

  resources :articles do
    resources :comments
    member do
      put "like" => "articles#upvote"
      put "unlike" => "articles#downvote"
    end

  end
  
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  acts_as_votable


  validates :title,:article_body, presence: true
  has_attached_file :photo, :styles => {:small => "600X600>"},
      :url => "/assets/:basename.:extension",
      :path => ":rails_root/app/assets/images/:basename.:extension"

      validates_attachment_presence :photo
      validates_attachment_content_type :photo, content_type: ["image/jpeg", "image/png"]
      validates_attachment_size :photo, :less_than =>5.megabytes


      
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :authenticate_user!,except:[:index, :show]
 
  # GET /articles
  # GET /articles.json


  def index
      @articles = Article.all.order(created_at: :desc).paginate(:page => params[:page], per_page: 7)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comments = @article.comments.order("created_at DESC").paginate(:page => params[:page], per_page: 2)
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    @article.autor = current_user.first_name

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
        format.js
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  #upvote_from user
  #downvote_from user
  def upvote
    @article.upvote_from current_user
    redirect_back(fallback_location: articles_path)

  end
  def downvote
    @article.downvote_from current_user
    redirect_back(fallback_location: articles_path)
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :article_body, :autor, :photo)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<h3><%= link_to article.title, article %></h3>
<p>
  Created by: 
  <strong>
    <%= article.autor %> 
  </strong> 
  <i class="time">
    <%= article.created_at.strftime("%b %d, %Y") %>
  </i>
</p>

<p>
  <%= image_tag(article.photo.url, class: "img-responsive") %>
  
</p>
<p>
  <%= truncate(article.article_body,length: 140) %>  
  <%= link_to 'Read more.', article %>
</p>

 

app/views/articles/_comments.html.erb
<div class="product-reviews">
    <% @comments.each do |comment| %>
        
            <p><strong><%= comment.user.first_name %></strong> <small><em style="float:right;"><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small></p>
           
            <p><%= comment.body %>
            <% if signed_in? && current_user.admin? %>
              <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, article_comment_path(comment.article, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>  
            </p>
            <hr>
    <% end %>
</div>

app/views/articles/_form.html.erb
<%= form_for(article, :html => { multipart: true }) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(article.errors.count, "error") %> 
        prohibited this article from being saved:
      </h2>
      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<form action="">
  <div class="field">
    <%= f.label :autor %> :
    <span><%= current_user.first_name %></span> 
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

    <%= f.hidden_field :user_id, value: current_user.id %>

  
  <div class="field">
    <%= f.label :article_body %>
    <%= f.text_area :article_body %>
  </div>

  <div>
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>

  

  <div class="actions">
    <%= f.submit  class: "btn btn-default btn-form"%>
  </div>
  </form>
<% end %>

app/views/articles/_new_comment.html.erb
<% if signed_in? %>
  <h4>Add a comment:</h4>
  <%= form_for([@article, @article.comments.build]) do |f| %>
    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body %>
    </p>
    
    <p>
      <%= f.submit "Submit" %>
    </p>
  <% end %>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article , class: "btn btn-default" %>
<%= link_to 'Back', articles_path , class: "btn btn-default" %>

app/views/articles/index.html.erb
<article class="container">

  <div class="top_article">     
    <%= render @articles.first(1) %>
  </div>

<h1>Articles</h1>
  <div class="container-fluid wrap">
    
    <div class="row">
      <% @articles.drop(1).each do |article| %>
        <div class="col-sm-6 col-md-6">
          <%= render article %>
          <div class="button">
              <% if (user_signed_in? && (current_user.id == article.user_id) || current_user.try(:admin?)) %>
                <%= link_to 'Edit', edit_article_path(article)  , class: "btn btn-outline-secondary btn-sm" %>
              
              <%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' }, 
              class: "btn btn-outline-secondary btn-sm" %>
              <% end %>
          </div>
          <hr class="line container-fluid">
        </div>

      <% end %>
    </div>
    <%= will_paginate @articles, inner_window: 1 , class: "apple_pagination" %>
  </div>
<br>
<% if (user_signed_in?) %>
  <%= link_to 'New Article', new_article_path  , class: "btn btn-default" %>
<% end %>
</article>

app/views/articles/new.html.erb
<article class="container min-height">  
  <h1>New Article</h1>
  
  <%= render 'form', article: @article %>
  
  <%= link_to 'Back', articles_path, class: "btn btn-default"   %>
</article>

app/views/articles/show.html.erb
<article class="container">
  
  <div class="wrap">
    <p>
      Created by: <strong><%= @article.autor %></strong>
      <i class="time">
        <%= @article.created_at.strftime("%b %d, %Y") %>
      </i>

      <div class="caption" style="float: right; margin-bottom: 20px;">
        <%= link_to like_article_path(@article), class: "like", remote: true, method: :put do %>
          <button type="button" class="btn btn-info btn-sm"  aria-label="Left Align">
            <span class="glyphicon glyphicon-thumbs-up  glyphicon-align-center" aria-hidden="true"></span>
            <span class="badge"><%= @article.get_upvotes.size %>  </span>
          </button>
        <% end %>
        <%= link_to unlike_article_path(@article), class: "like  ", remote: true, method: :put do %>
          <button type="button" class="btn btn-danger btn-sm"  aria-label="Left Align">
            <span class="glyphicon glyphicon-thumbs-down  glyphicon-align-center" aria-hidden="true"></span>
            <span class="badge"><%= @article.get_downvotes.size  %></span>
          </button>
        <% end %>
      </div>

    </p>
    <p>
      <%= image_tag(@article.photo.url, class: "img-responsive") %>
    </p>
    
    <h3 class="title">
      <%= @article.title%>
    </h3>
    <p>
      <%= simple_format @article.article_body, class: "txt_indent"%>
    </p>
    <%= render 'new_comment' %>
    <%= render 'comments' %>

    <%= will_paginate @comments, inner_window: 1 %>
  </div>
  <div class="button">
    <% if (user_signed_in? && (current_user.id == @article.user_id) || current_user.try(:admin?)) %>
      <%= link_to 'Edit', edit_article_path(@article)  , class: "btn btn-sm" %>
                
      <%= link_to 'Destroy', @article, method: :delete, data: { confirm: 'Are you sure?' }, 
                class: "btn btn-sm" %>
    <% end %>
  </div>
    <%= link_to 'Back', articles_path, class: "btn btn-default" %>
    
</article>