config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', path_names: { sign_in: 'login', sign_out: 'logout' }, :controllers => { registrations: 'user_registrations' }
  resources :users
  get 'static_pages/index'

  get 'static_pages/about'

  get 'static_pages/contact'
 
  root 'articles#index'

  post 'static_pages/thank_you'

  resources :articles do
    resources :comments
    member do
      put "like" => "articles#upvote"
      put "unlike" => "articles#downvote"
    end

  end
  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FishingWithMe</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

        <meta name="viewport" content="width=device-width, initial-scale=1">
        <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="content">
      <nav class="navbar navbar-inverse navbar-fixed-top"><!--  Nav  -->
            <div class="container-fluid">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a href="#index" class="navbar-brand">Fishing With Me</a>
              </div>
              <div class="collapse navbar-collapse" id="navbar-collapse">
                <ul class="nav navbar-nav">
                  <li class=<%= active_class(articles_path) %>><%= link_to 'Home', articles_path %></li>
                  <li class=<%= active_class(static_pages_about_path) %>><%= link_to 'About', static_pages_about_path %></li>
                  <li class=<%= active_class(static_pages_contact_path) %>><%= link_to 'Contact', static_pages_contact_path %></li>
                  <li>
                    <% if user_signed_in? %>
                      <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
                    <% else %>
                      <%= link_to('Login', new_user_session_path) %>
                    <% end %>
                  </li>
                  <li class="user-login dropdown">
                    <% if user_signed_in? %>
                      <a class="dropdown-toggle capitalize-name" data-toggle="dropdown" href="#" aria-expanded="true">
                        <% if current_user.try(:admin?) %>
                        Welcome: <span class= "admin"><%= current_user.first_name  %></span>
                        <% else %>  
                         Welcome: <%= current_user.first_name %>
                        <% end %>
                         <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                              <li>
                                <%= link_to 'Profile', user_path(current_user.id) %>
                              </li>
                              <li>
                                <%= link_to 'Settings', edit_user_registration_path %>
                              </li>
                            </ul>       
                      <% end %>
                  </li>
                  
                </ul>
                
              </div>
            </div>
      </nav>
          
          <% if notice %>  
            <p id="notice" class="alert alert-success" role="alert">
              <%= notice %>
            </p>
          <% end %>
          <% if alert %>  
            <p id="alert" class="alert alert-danger" role="alert">
              <%= alert %>
            </p>
          <% end %>
          <article class="container">
            <%= yield %>
          </article>
       </div>   
          <footer class="footer">
            
                  <p>&copy; Fishing With Me 2017 </p>
                
          </footer> 
        <p></p>
    </body>
</html>